"""Export service — PDF and JSON report export."""

import json
from typing import Optional


def export_json(report: dict) -> str:
    """Export a report as a formatted JSON string."""
    return json.dumps(report, indent=2, ensure_ascii=False)


def export_pdf_html(report: dict) -> str:
    """Generate HTML content for PDF export.
    
    Returns HTML string that can be converted to PDF via WeasyPrint.
    """
    claims_html = ""
    for claim in report.get("verified_claims", []):
        status_color = {
            "verified": "#22c55e",
            "conflict": "#ef4444",
            "unresolved": "#f59e0b",
        }.get(claim.get("status", ""), "#6b7280")

        claims_html += f"""
        <div style="border:1px solid #e5e7eb; border-radius:8px; padding:12px; margin:8px 0;">
            <p style="margin:0 0 4px 0;"><strong>{claim.get('claim', '')}</strong></p>
            <span style="color:{status_color}; font-weight:600;">{claim.get('status', '').upper()}</span>
            &mdash; Confidence: {claim.get('confidence', 0):.0f}%
        </div>
        """

    sources_html = ""
    for src in report.get("sources", []):
        sources_html += f"<li>{src.get('domain', '')} ({src.get('trust_tier', 'unknown')}) — Score: {src.get('trust_score', 0)}</li>"

    html = f"""
    <!DOCTYPE html>
    <html><head><meta charset="utf-8">
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; color: #1f2937; }}
        h1 {{ color: #6366f1; }}
        .meta {{ color: #6b7280; font-size: 14px; margin-bottom: 24px; }}
    </style>
    </head><body>
    <h1>WebIntel Report</h1>
    <div class="meta">
        <p>Query: <strong>{report.get('query', '')}</strong></p>
        <p>Mode: {report.get('mode', '')} | Type: {report.get('query_type', '')} | Confidence: {report.get('overall_confidence', 0):.0f}%</p>
        <p>Generated: {report.get('generated_at', '')}</p>
    </div>
    <h2>Verified Claims</h2>
    {claims_html}
    <h2>Sources</h2>
    <ul>{sources_html}</ul>
    <hr><p style="color:#9ca3af; font-size:12px;">Generated by WebIntel — Antigravity</p>
    </body></html>
    """
    return html


def generate_pdf(report: dict) -> Optional[bytes]:
    """Generate a PDF from a report. Returns bytes or None if WeasyPrint is unavailable."""
    try:
        from weasyprint import HTML
        html_content = export_pdf_html(report)
        return HTML(string=html_content).write_pdf()
    except ImportError:
        print("[Export] WeasyPrint not installed, PDF export unavailable")
        return None
    except Exception as e:
        print(f"[Export] PDF generation error: {e}")
        return None
